### PR TITLE
Change installation location

### PR DESCRIPTION
**Pull request by Carifio24**
Just a simple PR to get my feet wet with the Windows client. This modifies the installation location of the Windows client from `Microsoft Research\Microsoft WorldWide Telescope` to `American Astronomical Society\AAS WorldWide Telescope`.

### CODE REVIEW

**Comment by pkgw** [comment]
Closing and reopening to retry the CI. The builder machine should have woken up by now, hopefully.

**Comment by pkgw** [comment]
Yay, it worked! And the build artifacts include things that look like the right kinds of executables.

**Comment by pkgw** [comment]
@Carifio24 Please play around with the artifacts generated by the CI process, and let me know if/when you can confirm that the installer seems to be working correctly for you? I'll also try an installation on the Surface tablet I have. We should expect warnings about unsigned code since this is a PR.

**Comment by Carifio24** [comment]
@pkgw The installer from the CI is working correctly for me - the installation location is correct, and the client itself seems to be running fine.

**Comment by pkgw** [comment]
I checked out the signed artifacts and they seem to be OK. I still get some warnings about unrecognized software when launching the installer from a download, but that seems to be a separate layer of protection.

**Comment by astrojonathan** [comment]
We need to make sure that we test WWTRemote and make sure that we don't break planetarium and KIOSK installs that might assume install location. Just double-check there are no side effects of this.

**Comment by pkgw** [comment]
Yeah, we'll test as best we can, and also emphasize the change in the release notes. In general we'll make it clear that people with production deployments shouldn't update them without careful and thorough testing.

**Pull request merged**
