### PR TITLE
Lots of cleaning!

### PR DESCRIPTION
**Pull request by bluephoton**
I find it a bit hard to work with this code without some cleaning. I handled tons of Resharper issues in these changes. Some issues seems to be potential bugs so I left as is for further analysis. Most of changes are auto applied by Resharper with the exception of few updates i made to allow further refactoring.

Not sure if there is a way to extensively test, I just built and ran basic scenarios and all seemed to work fine.

This is a good point to pull this change and align with my fork, or else will be difficult to keep further refactoring in sync.

### CODE REVIEW

**Comment by kfogel** [comment]
Hey, @bluephoton, thanks.  

Now I wish we had finished and posted some development guidelines / coding style guidelines we are working on (see [this ticket](https://github.com/WorldWideTelescope/wwt-website/issues/3)), because that might have saved you some time, and encouraged discussion before making such a large change.

First, we can't land a massive set of changes all at once, because it's too hard to really review that much churn.  (Most open source projects have a similar policy.)

But in the case of this pull request, there are also some specific reasons why we don't want to merge it.  The WWT code uses explicit typing on purpose, for readability among other things, so changing everything to the generic "var" style isn't something we want.  More generally, we don't want to apply changes that affect only style, because they cause a shadow in the code history -- later, when we're using `git blame` and `git bisect` to track down a bug, the history would be cluttered with semantically insignificant but textually noisy changes.  Instead, we aim for the minimal textual change necessary to accomplish a behavioral goal.

Regarding the "build errors" fix (commit e11e689): do you really mean Resharper warnings, rather than actual build errors?  (A "build error" would be something that stops the build, and would be a high priority of course.)  The code does get some real warnings, I mean from the compiler not just from Resharper, but those are known & expected, and are unavoidable due to some of the techniques being used.

A thought: Maybe open up a specific new issue for a small, well-bounded problem you'd like to solve, discuss (even just briefly) the way you plan to solve it, and then send in the pull request for just that?

We're eager to work with you, and appreciate the effort you put in here.  I wish we had realized sooner and been able to discuss it, to save you time.  But if we start again with a more engaged process, we can probably start landing changes soon.

Best regards,
-Karl

**Comment by bluephoton** [comment]
Hello Karl, Thanks a lot for your reply! 

I totally understand. I didn't expect this to be merged but thought I send the request anyway in case you may have a automated test bed to verify. And no worries, I didn't spend much time really as most of the changes were applied automatically by Resharper at the project level. Publishing guidelines and styles is a great idea.

I also agree the use of var is sometimes discouraged, although modern IDEs and tools like Resharper makes it much easier to discover and navigate code, that why I don't mind the use of var.

As for the build errors, these were local to my fork as i missed to commit some files that were not tracked.

Since I'm brand new to the WWT code, my goal was to get it to some point where I can comfortably  read/understand/refactor. The code as is generates tons of resharper warnings (some of them are potential bugs) and, I find it bit discouraging :)

I'll keep working on my local copy as a playground for now, and will keep an eye for published guidelines and will be happy to contribute in the future with smaller and scoped changes.

-Mohamed

**Comment by kfogel** [comment]
Hey, @bluephoton , thanks for the very understanding response!  We'll get the guidelines up as soon as we can.  In the meantime, though, maybe try looking through the current issues and picking a small one to fix?  That can be a good way to learn about a codebase from the inside, and it's an easy way to come up with a smaller & scoped change...  We're watching the issue tracker and will try to answer any questions you ask, of course.

**Comment by bluephoton** [comment]
Sure thing, will take a look. Thanks for letting me know!!!

**Pull request closed without merging**
